baseurl = "http://example.org/"
languageCode = "en-us"
title = "BioInterns"
theme = "cards"

# quanti vuoi vederne per ogni pagina
# 6 vuol dire tipo 2 righe, con 3 cards per riga
paginate = 6

[params]
  builtBy = "Valentina Lorenzi"
  defaultImage = "gopher.jpg"

  #DISABILITATI
  #facebook = ""
  #quora = ""
  #twitter = "http://twitter.com/bul_ikana"
  #github = "http://github.com/bul-ikana"
  #email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  description = "Benvenuto su BioInterns! Sei uno studente di triennale o magistrale di Biologia/Biotecnologie o affini? Scorri tra le pagine per conoscere opportunit√† di tirocinio all'estero pagate nei migliori atenei del mondo."

  [params.copyright]
     name = "Valentina Lorenzi"
     link = "https://github.com/valelorenzi9"

